export interface WageYearData {
  id: string;
  year: string;
  active: boolean;
  isFileUploaded?: boolean;
  pdfFile?: File | null;
  fileURL?: string;
  pdfUrl?: string;
  workPeriod: string;
  workPlace: string;
  businessNumber: string;
  companyRegNum?: string;
  birthDate: string;
  
  salaryTotal: string | number;
  totalSalary?: string | number;
  taxBase: string | number;
  childReduction: string | number;
  appliedTaxReduction?: string | number;
  childDeduction?: string | number;
  stdTaxCredit?: string | number;
  decisionTax: string | number;
  originalDeterminedTax?: string | number;
  localTax: string | number;
  taxRefundTotal: string | number;
  childReductionApply: string;
  childReductionApplyAmt: string | number;
  childDeductionApplyAmt?: string | number;
  decisionTaxApplyAmt: string | number;
  recalcDeterminedTax?: string | number;
  localTaxApplyAmt: string | number;
  recalcLocalTax?: string | number;
  decisionTaxRefundAmt: string | number;
  refundExpectNational: string | number;
  expectedRefundNational?: string | number;
  refundExpectLocal: string | number;
  expectedRefundLocal?: string | number;
  courtFee: string | number;
  expectedFeeAmt: string | number;
  isReductionEligible: string;
  correctionFileUrl: string;
  isRefundOverridden?: boolean;
  rentRefundTotal?: string | number;
  rentRefundExpectNational?: string | number;
  rentRefundExpectLocal?: string | number;
  dependentRefundTotal?: string | number;
}

export interface FreelancerYearData {
  active: boolean;
  isFileUploaded: boolean;
  pdfFile?: File | null;
  fileURL?: string;
  pdfUrl?: string;
  workPlace: string;
  businessNumber: string;
  totalIncome: string;
  withholdingTax3: string;
  localTax03: string;
  totalWithholding33: string;
  refundExpectNational: string;
  refundExpectLocal: string;
  courtFee: string;
  expectedFeeAmt: string;
  incomeTypeCode: string;
  isNonRefundable: boolean;
}

export interface RegistrationForm {
  companyAddress: string;
  companyPhone: string;
  companyIndustry: string;
  clientId: string;
  serial: number;
  name: string;
  foreignerNumber: string;
  nationality: string;
  managerName: string;
  telecom: string;
  phone: string;
  visaType: string;
  residentAddress: string;
  visaExpiry: string;
  isMonthlyRent: string;
  landlordName: string;
  landlordRegNum: string;
  rentHousingType: string;
  rentHousingSize: string;
  rentContractor: string;
  rentHouseholder: string;
  rentAllHouseholdsNoHouse: string;
  monthlyRentFee: string;
  rentLeaseStart: string;
  rentLeaseEnd: string;
  rentContractDocFile: File | null;
  rentContractDocUrl: string;
  rentReceiptDocFile: File | null;
  rentReceiptDocUrl: string;
  refundBankName: string;
  refundBank: string;
  refundStatus: string;
  residentRegisterAddress: string;
  deductionSubmissionStatus: string;
  deductionApplyPeriod: string;
  deductionSentDate: string;
  claimRequestDate: string;
  claimCompleteDate: string;
  additionalApplyPerformance: string;
  feePaymentStatus: string;
  taxReductionApplyDateStart: string;
  taxReductionApplyDateEnd: string;
  years: WageYearData[];
  freelancerYears: Record<string, FreelancerYearData>;
  deletedYearIds: string[];
  snsName: string;
  snsAddress: string;
  hometaxId: string;
  hometaxPw: string;
  customerGrade: string;
  greenContractDate: string;
  consultMemo: string;
  refundPerformance: string;
  refundPerformanceDate: string;
  feeReceivedPerformance: string;
  feeReceivedDate: string;
  dependentsCount: number;
  seniorCount: number;
  disabledCount: number;
  childCount: number;
  familyDocUrl: string[];
  remittanceDocUrl: string[];
  familyDocFile: File[];
  remittanceDocFile: File[];
  dependents?: {
    name: string;
    rrn: string;
    relation?: string;
    isBasic?: boolean;
    isSenior?: boolean;
    isDisabled?: boolean;
    isChild?: boolean;
  }[];
}
